
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Modal from "./ui/modal";
import LoginButton from "./ui/login-button";
import MainNav from "./ui/main-nav";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Thkim Container",
  description: "Generated by thkim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko">
      <body className={poppins.className}>
      <Modal />
      <main className="">
        <header className="flex justify-between items-center">
          <div id="logo-wrap" className="p-3 m-2">
            <Link href={"/"} className="px-4 py-2 border rounded-md border-slate-100">thkim Container</Link>
          </div>
          <MainNav />
          <LoginButton />
        </header>
      </main>
      {children}
      </body>
    </html>
  );
}
